import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "../globals.css";
import { AppProvider } from "./Provider/AppProvider";

export const metadata: Metadata = {
  title: "Boss Nation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
